#include <iostream>
#include "rlutil.h"
#include "comoJugar.h"

void mostrarInstrucciones()
{
        rlutil::cls();
        rlutil::locate(34, 2); 
        std::cout << "====================================================";
        rlutil::locate(34, 3);
        std::cout << "                       TUTORIAL                     ";
        rlutil::locate(34, 4); 
        std::cout << "====================================================";
        rlutil::locate(36, 6); 
        std::cout << "OBJETIVO";
        rlutil::locate(36, 8); 
        std::cout << "Debes sellar a los cinco demonios";
        rlutil::locate(36, 9);
        std::cout << "antes de que amanezca";
        rlutil::locate(36, 11);
        std::cout << "Dispones de 15 invocaciones para completar";
        rlutil::locate(36, 12);
        std::cout << "el ritual de sellado.";
        rlutil::locate(34, 14);
        std::cout << "====================================================";
        rlutil::locate(36, 16);
        std::cout << "DEMONIOS Y CONDICIONES";
        rlutil::locate(36, 18);
        std::cout << "Baramos     -> Obtener un par o iguales";
        rlutil::locate(36, 19); 
        std::cout << "Dracolord   -> Obtener suma exacta de 7.";
        rlutil::locate(36, 20); 
        std::cout << "Darck       -> Obtener numeros consecutivos.";
        rlutil::locate(36, 21); 
        std::cout << "WhiteKing   -> Obtener suma mayor o igual a 10.";
        rlutil::locate(36, 22);
        std::cout << "Lazamanus   -> Obtener doble 5 o doble 6.";
        rlutil::locate(34, 24);
        std::cout << "====================================================";
        rlutil::locate(36, 25); 
        std::cout << "Toca cualquier tecla para seguir leyendo...";
        rlutil::anykey();
        rlutil::cls();
        rlutil::locate(34, 2);
        std::cout << "====================================================";
        rlutil::locate(34, 3);
        std::cout << "                     COMO JUGAR                     ";
        rlutil::locate(34, 4);
        std::cout << "====================================================";
        rlutil::locate(36, 6);
        std::cout << "En cada turno lanzaras dos dados.";
        rlutil::locate(36, 8); 
        std::cout << "Si la tirada cumple con la condicion de un";
        rlutil::locate(36, 9);
        std::cout << "demonio que aun este libre, sera sellado.";
        rlutil::locate(36, 11);
        std::cout << "Si una tirada cumple varias condiciones,";
        rlutil::locate(36, 12);
        std::cout << "podes elegir solo un demonio para sellar.";
        rlutil::locate(36, 14);
        std::cout << "Ejemplo:";
        rlutil::locate(36, 15);
        std::cout << "Los dados muestran";
        rlutil::saveDefaultColor();
        rlutil::setColor(12);
        rlutil::locate(55, 15);
        std::cout << "[6] [6] ";
        rlutil::resetColor();
        rlutil::locate(46, 17);
        std::cout << "Baramos    -> Iguales o Par";
        rlutil::locate(46, 18);
        std::cout << "WhiteKing  -> Suma mayor que 10";
        rlutil::locate(46, 19);
        std::cout << "Lazamanus  -> Doble 6";
        rlutil::locate(46, 21);
        std::cout << "Podras elegir a uno de ellos para sellar.";
        rlutil::locate(34, 23);
        std::cout << "====================================================";
        rlutil::locate(36, 24);
        std::cout << "Toca cualquier tecla para seguir leyendo...";
        rlutil::anykey();
        rlutil::cls();
        rlutil::locate(34, 2); 
        std::cout << "====================================================";
        rlutil::locate(34, 3); 
        std::cout << "                     ADVERTENCIA                    ";
        rlutil::locate(34, 4);
        std::cout << "====================================================";
        rlutil::locate(36, 6);
        std::cout << "Si una tirada no coincide con ningun demonio";
        rlutil::locate(36, 7);
        std::cout << "libre, la invocacion se pierde.";
        rlutil::locate(36, 9);
        std::cout << "Cada lanzamiento consume una invocacion,";
        rlutil::locate(36, 10); 
        std::cout << "sin importar el resultado.";
        rlutil::locate(36, 12); 
        std::cout << "Si agotas las 15 invocaciones y aun queda";
        rlutil::locate(36, 13); 
        std::cout << "algun demonio libre, perderas la partida.";
        rlutil::locate(34, 15); 
        std::cout << "====================================================";
        rlutil::locate(36, 16);
        std::cout << "Toca cualquier tecla para seguir leyendo...";
        rlutil::anykey();
        rlutil::cls();
        rlutil::locate(34, 2);
        std::cout << "====================================================";
        rlutil::locate(34, 3);
        std::cout << "                  ATAQUE DE LAZAMANUS               ";
        rlutil::locate(34, 4);
        std::cout << "====================================================";
        rlutil::locate(34, 6);
        std::cout << "Mientras Lazamanus permanezca libre,";
        rlutil::locate(34, 7);
        std::cout << "vigilara cada uno de tus errores.";
        rlutil::locate(34, 9);
        std::cout << "Al finalizar una invocacion fallida,";
        rlutil::locate(34, 10);
        std::cout << "Lazamanus te hara lanzar tres dados.";
        rlutil::locate(34, 12);
        std::cout << "Si al tirar, los dados muestran";
        rlutil::saveDefaultColor();
        rlutil::setColor(12);
        rlutil::locate(66, 12);
        std::cout << "[6] [6] [6] ";
        rlutil::resetColor();
        rlutil::locate(34, 14);
        std::cout << "Tu alma sera atrapada dentro del";
        rlutil::locate(34, 15); 
        std::cout << "Necronomicon y la partida terminara";
        rlutil::locate(34, 16);
        std::cout << "inmediatamente de cuantos demonios.";
        rlutil::locate(34, 17);
        std::cout << "hayas sellado hasta el momento.";
        rlutil::locate(34, 19); 
        std::cout << "Buena suerte, descendiente.";
        rlutil::locate(34, 21);
        std::cout << "====================================================";
        rlutil::locate(34, 22);
        std::cout << "Toca cualquier tecla para volver al Menu De Juego...";
        rlutil::anykey();
        rlutil::cls();
}

void mostrarHistoria()
{
        rlutil::cls();
        rlutil::locate(34, 2); 
        std::cout << "====================================================";
        rlutil::locate(34, 3); 
        std::cout << "                  LOS CINCO DEMONIOS                ";
        rlutil::locate(34, 4); 
        std::cout << "====================================================";
        rlutil::locate(51, 6); 
        std::cout << "Invierno de 2026.";
        rlutil::locate(36, 8); 
        std::cout << "Durante generaciones, la familia Dieser custodio";
        rlutil::locate(39, 9); 
        std::cout << "un antiguo libro prohibido conocido como el";
        rlutil::locate(36, 10);
        std::cout << "Necronomicon. Oculto bajo siete cerraduras de plata,";
        rlutil::locate(48, 12); 
        std::cout << "Pero algo salio mal.";
        rlutil::locate(34, 14);
        std::cout << "Un grupo de cultistas logro ingresar a la mansion y";
        rlutil::locate(34, 15);
        std::cout << "realizo un ritual impensado. Cuando llegaste, ya era";
        rlutil::locate(34, 16); 
        std::cout << "demasiado tarde. El libro estaba abierto y los cinco";
        rlutil::locate(36, 17); 
        std::cout << "sigilos que mantenian cautivas a las entidades del";
        rlutil::locate(40, 18);
        std::cout << "abismo brillaban con un resplandor rojo.";
        rlutil::locate(40, 21); 
        std::cout << "Toca cualquier tecla para seguir leyendo...";
        rlutil::anykey();
        rlutil::cls();
        rlutil::saveDefaultColor();
        rlutil::setColor(12);
        rlutil::locate(35, 6); 
        std::cout << "Baramos, Dracolord, Drack, WhiteKing y Lazamanus";
        rlutil::resetColor();
        rlutil::locate(41, 8); 
        std::cout << "Los cinco demonios han sido liberados.";
        rlutil::locate(36, 10);  
        std::cout << "Armado unicamente con el Necronomicon y los dados";
        rlutil::locate(39, 11); 
        std::cout << "de hueso heredados de tus antepasados, deberas";
        rlutil::locate(41, 12); 
        std::cout << "completar el ritual antes del amanecer.";
        rlutil::locate(46, 14);  
        std::cout << "Dispones de 15 invocaciones.";
        rlutil::locate(39, 16); 
        std::cout << "Si logras sellar a las cinco entidades, el mundo";
        rlutil::locate(46, 17);
        std::cout << "estara a salvo una vez mas.";
        rlutil::locate(40, 20); 
        std::cout << "Toca cualquier tecla para seguir leyendo...";
        rlutil::anykey();
        rlutil::cls();
        rlutil::locate(54, 6);
        std::cout << "Si fallas...";
        rlutil::locate(34, 9); 
        std::cout << "Tu alma quedara atrapada entre las paginas del libro";
        rlutil::locate(40, 10); 
        std::cout << "hasta que otro descendiente repita el ritual";
        rlutil::locate(47, 11); 
        std::cout << "y logre por fin liberarte.";
        rlutil::locate(40, 13); 
        std::cout << "Solo vos podes completar el ritual de sellado.";
        rlutil::locate(36, 15); 
        std::cout << "Tenes 15 invocaciones antes del amanecer para sellar";
        rlutil::locate(54, 16);
        std::cout << "a los demonios.";
        rlutil::locate(43, 18);
        std::cout << "El destino del mundo esta en tus manos.";
        rlutil::locate(53, 20);
        std::cout << "Buena Suerte...";
        rlutil::locate(34, 22); 
        std::cout << "====================================================";
        rlutil::locate(34, 23); 
        std::cout << "Toca cualquier tecla para volver al Menu Principal...";
        rlutil::anykey();
}